#pragma once
#include <unordered_map>
namespace ZScript {
	enum TokenType {
		LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
		COMMA, DOT, MINUS, PLUS, SEMICOLON, NEW_LINE, SLASH, STAR,

		BANG, BANG_EQUAL,
		EQUAL, EQUAL_EQUAL,
		GREATER, GREATER_EQUAL,
		LESS, LESS_EQUAL,

		IDENTIFIER, STRING, NUMBER,

		AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL, OR,
		PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE,

		ENOF
	};
	enum VarType {
		VAR_BOOLEAN, VAR_NUMBER, VAR_STRING, VAR_CALLABLE, VAR_FUNCTION, VAR_CFUNCTION, VAR_LIGHTUSERDATA, VAR_USERDATA, VAR_NIL
	};
}
